version: '3'
services:
  jenkins:
   build:
      context: .
   ports:
     - '80:8080'
     - '50000:50000'
   volumes:
      - './jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/user/bin/docker'

   restart: always
  